import { createContext, useState, useContext } from 'react'

const LanguageContext = createContext()

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}

export const translations = {
  en: {
    name: 'English',
    home: 'Home',
    resources: 'Resources',
    login: 'Login',
    getStarted: 'Get Started',
    tagline: 'Practical farming techniques and simple projects',
    learnModern: 'Learn Modern Farming Techniques',
    heroDesc: 'From soil health to water conservation, explore practical guides designed for farmers of all scales.',
    coreResources: 'Core Resources',
    soilHealth: 'Soil Health 101',
    soilDesc: 'Improve soil fertility with compost, mulching, and cover crops. Build healthy soil ecosystems.',
    waterConservation: 'Water Conservation',
    waterDesc: 'Simple irrigation and rainwater harvesting techniques for small farms. Save water, save costs.',
    pestManagement: 'Pest Management',
    pestDesc: 'Low-cost, natural methods to manage pests and protect crops without harsh chemicals.',
    agriculturePlans: 'Agriculture Plans',
    viewDetails: 'View Details',
    selectLanguage: 'Select Language',
  },
  hi: {
    name: 'हिंदी',
    home: 'होम',
    resources: 'संसाधन',
    login: 'लॉगिन',
    getStarted: 'शुरू करें',
    tagline: 'व्यावहारिक खेती तकनीक और सरल परियोजनाएं',
    learnModern: 'आधुनिक खेती तकनीक सीखें',
    heroDesc: 'मिट्टी के स्वास्थ्य से लेकर जल संरक्षण तक, सभी पैमानों के किसानों के लिए डिज़ाइन की गई व्यावहारिक मार्गदर्शिकाएँ।',
    coreResources: 'मुख्य संसाधन',
    soilHealth: 'मिट्टी स्वास्थ्य 101',
    soilDesc: 'खाद, मल्चिंग और कवर फसलों से मिट्टी की उर्वरता में सुधार करें। स्वस्थ मिट्टी पारिस्थितिकी तंत्र बनाएं।',
    waterConservation: 'जल संरक्षण',
    waterDesc: 'छोटे खेतों के लिए सरल सिंचाई और वर्षा जल संचयन तकनीक। पानी बचाएं, लागत बचाएं।',
    pestManagement: 'कीट प्रबंधन',
    pestDesc: 'कठोर रसायनों के बिना कीटों को प्रबंधित करने और फसलों की रक्षा के लिए कम लागत वाली प्राकृतिक विधियाँ।',
    agriculturePlans: 'कृषि योजनाएं',
    viewDetails: 'विवरण देखें',
    selectLanguage: 'भाषा चुनें',
  },
  ta: {
    name: 'தமிழ்',
    home: 'முகப்பு',
    resources: 'வளங்கள்',
    login: 'உள்நுழைய',
    getStarted: 'தொடங்குக',
    tagline: 'நடைமுறை விவசாய நுட்பங்கள் மற்றும் எளிய திட்டங்கள்',
    learnModern: 'நவீன விவசாய நுட்பங்களைக் கற்றுக்கொள்ளுங்கள்',
    heroDesc: 'மண் ஆரோக்கியம் முதல் நீர் பாதுகாப்பு வரை, அனைத்து அளவிலான விவசாயிகளுக்காக வடிவமைக்கப்பட்ட நடைமுறை வழிகாட்டிகள்.',
    coreResources: 'முக்கிய வளங்கள்',
    soilHealth: 'மண் ஆரோக்கியம் 101',
    soilDesc: 'உரம், மல்ச்சிங் மற்றும் கவர் பயிர்களால் மண் வளத்தை மேம்படுத்துங்கள். ஆரோக்கியமான மண் சுற்றுச்சூழல் அமைப்புகளை உருவாக்குங்கள்.',
    waterConservation: 'நீர் பாதுகாப்பு',
    waterDesc: 'சிறிய பண்ணைகளுக்கான எளிய நீர்ப்பாசனம் மற்றும் மழை நீர் சேகரிப்பு நுட்பங்கள். நீரைச் சேமியுங்கள், செலவைக் குறைக்கவும்.',
    pestManagement: 'பூச்சி மேலாண்மை',
    pestDesc: 'கடுமையான இரசாயனங்கள் இல்லாமல் பூச்சிகளை நிர்வகிக்கவும் பயிர்களைப் பாதுகாக்கவும் குறைந்த செலவில் இயற்கை முறைகள்.',
    agriculturePlans: 'விவசாய திட்டங்கள்',
    viewDetails: 'விவரங்களைக் காண்க',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
  },
  te: {
    name: 'తెలుగు',
    home: 'హోమ్',
    resources: 'వనరులు',
    login: 'లాగిన్',
    getStarted: 'ప్రారంభించండి',
    tagline: 'ప్రాక్టికల్ వ్యవసాయ పద్ధతులు మరియు సులభమైన ప్రాజెక్టులు',
    learnModern: 'ఆధునిక వ్యవసాయ పద్ధతులను నేర్చుకోండి',
    heroDesc: 'నేల ఆరోగ్యం నుండి నీటి సంరక్షణ వరకు, అన్ని స్థాయిల రైతుల కోసం రూపొందించిన ప్రాక్టికల్ గైడ్‌లు.',
    coreResources: 'ప్రధాన వనరులు',
    soilHealth: 'నేల ఆరోగ్యం 101',
    soilDesc: 'కంపోస్ట్, మల్చింగ్ మరియు కవర్ పంటలతో నేల సారవంతత మెరుగుపరచండి. ఆరోగ్యకరమైన నేల పర్యావరణ వ్యవస్థలను నిర్మించండి.',
    waterConservation: 'నీటి సంరక్షణ',
    waterDesc: 'చిన్న పొలాల కోసం సులభమైన నీటిపారుదల మరియు వర్షపు నీటి సేకరణ పద్ధతులు. నీటిని ఆదా చేయండి, ఖర్చులను ఆదా చేయండి.',
    pestManagement: 'పెస్ట్ మేనేజ్‌మెంట్',
    pestDesc: 'కఠినమైన రసాయనాలు లేకుండా తెగుళ్లను నిర్వహించడానికి మరియు పంటలను రక్షించడానికి తక్కువ ఖర్చుతో కూడిన సహజ పద్ధతులు.',
    agriculturePlans: 'వ్యవసాయ ప్రణాళికలు',
    viewDetails: 'వివరాలు చూడండి',
    selectLanguage: 'భాషను ఎంచుకోండి',
  },
  bn: {
    name: 'বাংলা',
    home: 'হোম',
    resources: 'সম্পদ',
    login: 'লগইন',
    getStarted: 'শুরু করুন',
    tagline: 'ব্যবহারিক কৃষি কৌশল এবং সহজ প্রকল্প',
    learnModern: 'আধুনিক কৃষি কৌশল শিখুন',
    heroDesc: 'মাটির স্বাস্থ্য থেকে জল সংরক্ষণ পর্যন্ত, সব স্কেলের কৃষকদের জন্য ডিজাইন করা ব্যবহারিক গাইড অন্বেষণ করুন।',
    coreResources: 'মূল সম্পদ',
    soilHealth: 'মাটি স্বাস্থ্য 101',
    soilDesc: 'কম্পোস্ট, মালচিং এবং কভার ফসলের মাধ্যমে মাটির উর্বরতা উন্নত করুন। স্বাস্থ্যকর মাটির ইকোসিস্টেম তৈরি করুন।',
    waterConservation: 'জল সংরক্ষণ',
    waterDesc: 'ছোট খামারের জন্য সহজ সেচ এবং বৃষ্টির জল সংগ্রহের কৌশল। জল সাশ্রয় করুন, খরচ সাশ্রয় করুন।',
    pestManagement: 'কীটপতঙ্গ ব্যবস্থাপনা',
    pestDesc: 'কঠোর রাসায়নিক ছাড়া কীটপতঙ্গ পরিচালনা এবং ফসল রক্ষার জন্য কম খরচের প্রাকৃতিক পদ্ধতি।',
    agriculturePlans: 'কৃষি পরিকল্পনা',
    viewDetails: 'বিস্তারিত দেখুন',
    selectLanguage: 'ভাষা নির্বাচন করুন',
  },
  mr: {
    name: 'मराठी',
    home: 'होम',
    resources: 'संसाधने',
    login: 'लॉगिन',
    getStarted: 'सुरु करा',
    tagline: 'व्यावहारिक शेती तंत्र आणि सोपे प्रकल्प',
    learnModern: 'आधुनिक शेती तंत्र शिका',
    heroDesc: 'मातीच्या आरोग्यापासून पाणी संवर्धनापर्यंत, सर्व स्तरावरील शेतकऱ्यांसाठी डिझाइन केलेल्या व्यावहारिक मार्गदर्शकांचा अभ्यास करा।',
    coreResources: 'मुख्य संसाधने',
    soilHealth: 'माती आरोग्य 101',
    soilDesc: 'कंपोस्ट, मल्चिंग आणि कव्हर पिकांसह मातीची सुपीकता सुधारा. निरोगी माती इकोसिस्टम तयार करा.',
    waterConservation: 'पाणी संवर्धन',
    waterDesc: 'लहान शेतांसाठी साधे सिंचन आणि पावसाचे पाणी साठवण्याची तंत्रे. पाणी वाचवा, खर्च वाचवा.',
    pestManagement: 'कीड व्यवस्थापन',
    pestDesc: 'कठोर रसायनांशिवाय किडींचे व्यवस्थापन करण्यासाठी आणि पिकांचे संरक्षण करण्यासाठी कमी खर्चाच्या नैसर्गिक पद्धती.',
    agriculturePlans: 'शेती योजना',
    viewDetails: 'तपशील पहा',
    selectLanguage: 'भाषा निवडा',
  },
  gu: {
    name: 'ગુજરાતી',
    home: 'હોમ',
    resources: 'સંસાધનો',
    login: 'લૉગિન',
    getStarted: 'શરૂ કરો',
    tagline: 'વ્યવહારુ ખેતી તકનીકો અને સરળ પ્રોજેક્ટ્સ',
    learnModern: 'આધુનિક ખેતી તકનીકો શીખો',
    heroDesc: 'માટીના સ્વાસ્થ્યથી લઈને પાણી સંરક્ષણ સુધી, તમામ સ્તરના ખેડૂતો માટે ડિઝાઇન કરેલ વ્યવહારુ માર્ગદર્શિકાઓનું અન્વેષણ કરો.',
    coreResources: 'મુખ્ય સંસાધનો',
    soilHealth: 'માટી સ્વાસ્થ્ય 101',
    soilDesc: 'ખાતર, મલ્ચિંગ અને આવરણ પાક સાથે માટીની ઉર્વરતા સુધારો. સ્વસ્થ માટી ઇકોસિસ્ટમ બનાવો.',
    waterConservation: 'પાણી સંરક્ષણ',
    waterDesc: 'નાના ખેતરો માટે સરળ સિંચાઈ અને વરસાદી પાણી સંગ્રહ તકનીકો. પાણી બચાવો, ખર્ચ બચાવો.',
    pestManagement: 'જીવાત વ્યવસ્થાપન',
    pestDesc: 'કઠોર રસાયણો વિના જીવાતોનું સંચાલન અને પાકની સુરક્ષા માટે ઓછા ખર્ચની કુદરતી પદ્ધતિઓ.',
    agriculturePlans: 'કૃષિ યોજનાઓ',
    viewDetails: 'વિગતો જુઓ',
    selectLanguage: 'ભાષા પસંદ કરો',
  },
  kn: {
    name: 'ಕನ್ನಡ',
    home: 'ಮುಖಪುಟ',
    resources: 'ಸಂಪನ್ಮೂಲಗಳು',
    login: 'ಲಾಗಿನ್',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    tagline: 'ಪ್ರಾಯೋಗಿಕ ಕೃಷಿ ತಂತ್ರಗಳು ಮತ್ತು ಸರಳ ಯೋಜನೆಗಳು',
    learnModern: 'ಆಧುನಿక ಕೃಷಿ ತಂತ್ರಗಳನ್ನು ಕಲಿಯಿರಿ',
    heroDesc: 'ಮಣ್ಣಿನ ಆರೋಗ್ಯದಿಂದ ನೀರಿನ ಸಂರಕ್ಷಣೆಯವರೆಗೆ, ಎಲ್ಲಾ ಪ್ರಮಾಣದ ರೈತರಿಗಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಿದ ಪ್ರಾಯೋಗಿಕ ಮಾರ್ಗದರ್ಶಿಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.',
    coreResources: 'ಮುಖ್ಯ ಸಂಪನ್ಮೂಲಗಳು',
    soilHealth: 'ಮಣ್ಣಿನ ಆರೋಗ್ಯ 101',
    soilDesc: 'ಕಂಪೋಸ್ಟ್, ಮಲ್ಚಿಂಗ್ ಮತ್ತು ಕವರ್ ಬೆಳೆಗಳೊಂದಿಗೆ ಮಣ್ಣಿನ ಫಲವತ್ತತೆಯನ್ನು ಸುಧಾರಿಸಿ. ಆರೋಗ್ಯಕರ ಮಣ್ಣಿನ ಪರಿಸರ ವ್ಯವಸ್ಥೆಗಳನ್ನು ನಿರ್ಮಿಸಿ.',
    waterConservation: 'ನೀರಿನ ಸಂರಕ್ಷಣೆ',
    waterDesc: 'ಸಣ್ಣ ಜಮೀನುಗಳಿಗೆ ಸರಳ ನೀರಾವರಿ ಮತ್ತು ಮಳೆ ನೀರು ಸಂಗ್ರಹಣೆ ತಂತ್ರಗಳು. ನೀರನ್ನು ಉಳಿಸಿ, ವೆಚ್ಚವನ್ನು ಉಳಿಸಿ.',
    pestManagement: 'ಕೀಟ ನಿರ್ವಹಣೆ',
    pestDesc: 'ಕಠಿಣ ರಾಸಾಯನಿಕಗಳಿಲ್ಲದೆ ಕೀಟಗಳನ್ನು ನಿರ್ವಹಿಸಲು ಮತ್ತು ಬೆಳೆಗಳನ್ನು ರಕ್ಷಿಸಲು ಕಡಿಮೆ ವೆಚ್ಚದ ನೈಸರ್ಗಿಕ ವಿಧಾನಗಳು.',
    agriculturePlans: 'ಕೃಷಿ ಯೋಜನೆಗಳು',
    viewDetails: 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    selectLanguage: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
  },
  ml: {
    name: 'മലയാളം',
    home: 'ഹോം',
    resources: 'വിഭവങ്ങൾ',
    login: 'ലോഗിൻ',
    getStarted: 'ആരംഭിക്കുക',
    tagline: 'പ്രായോഗിക കാർഷിക സാങ്കേതികതകളും ലളിതമായ പ്രോജക്‌ടുകളും',
    learnModern: 'ആധുനിക കാർഷിക സാങ്കേതികതകൾ പഠിക്കുക',
    heroDesc: 'മണ്ണിന്റെ ആരോഗ്യം മുതൽ ജല സംരക്ഷണം വരെ, എല്ലാ തോതിലുള്ള കർഷകർക്കായി രൂപകൽപ്പന ചെയ്ത പ്രായോഗിക ഗൈഡുകൾ പര്യവേക്ഷണം ചെയ്യുക.',
    coreResources: 'പ്രധാന വിഭവങ്ങൾ',
    soilHealth: 'മണ്ണ് ആരോഗ്യം 101',
    soilDesc: 'കമ്പോസ്റ്റ്, മൾച്ചിംഗ്, കവർ വിളകൾ എന്നിവ ഉപയോഗിച്ച് മണ്ണിന്റെ ഫലഭൂയിഷ്ഠത മെച്ചപ്പെടുത്തുക. ആരോഗ്യകരമായ മണ്ണ് പരിസ്ഥിതി വ്യവസ്ഥകൾ നിർമ്മിക്കുക.',
    waterConservation: 'ജല സംരക്ഷണം',
    waterDesc: 'ചെറുകിട ഫാമുകൾക്കുള്ള ലളിതമായ ജലസേചനവും മഴവെള്ള സംഭരണ സാങ്കേതികതകളും. വെള്ളം ലാഭിക്കുക, ചെലവ് ലാഭിക്കുക.',
    pestManagement: 'കീട നിയന്ത്രണം',
    pestDesc: 'കഠിനമായ രാസവസ്തുക്കൾ ഇല്ലാതെ കീടങ്ങളെ നിയന്ത്രിക്കാനും വിളകൾ സംരക്ഷിക്കാനും കുറഞ്ഞ ചെലവിൽ പ്രകൃതിദത്ത രീതികൾ.',
    agriculturePlans: 'കാർഷിക പദ്ധതികൾ',
    viewDetails: 'വിശദാംശങ്ങൾ കാണുക',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
  },
  pa: {
    name: 'ਪੰਜਾਬੀ',
    home: 'ਹੋਮ',
    resources: 'ਸਰੋਤ',
    login: 'ਲਾਗਿਨ',
    getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
    tagline: 'ਵਿਹਾਰਕ ਖੇਤੀਬਾੜੀ ਤਕਨੀਕਾਂ ਅਤੇ ਸਰਲ ਪ੍ਰੋਜੈਕਟ',
    learnModern: 'ਆਧੁਨਿਕ ਖੇਤੀਬਾੜੀ ਤਕਨੀਕਾਂ ਸਿੱਖੋ',
    heroDesc: 'ਮਿੱਟੀ ਦੀ ਸਿਹਤ ਤੋਂ ਲੈ ਕੇ ਪਾਣੀ ਦੀ ਬਚਤ ਤੱਕ, ਸਾਰੇ ਪੈਮਾਨਿਆਂ ਦੇ ਕਿਸਾਨਾਂ ਲਈ ਤਿਆਰ ਕੀਤੇ ਵਿਹਾਰਕ ਗਾਈਡਾਂ ਦੀ ਪੜਚੋਲ ਕਰੋ।',
    coreResources: 'ਮੁੱਖ ਸਰੋਤ',
    soilHealth: 'ਮਿੱਟੀ ਸਿਹਤ 101',
    soilDesc: 'ਖਾਦ, ਮਲਚਿੰਗ ਅਤੇ ਕਵਰ ਫਸਲਾਂ ਨਾਲ ਮਿੱਟੀ ਦੀ ਉਪਜਾਊ ਸ਼ਕਤੀ ਵਿੱਚ ਸੁਧਾਰ ਕਰੋ। ਸਿਹਤਮੰਦ ਮਿੱਟੀ ਦੇ ਵਾਤਾਵਰਣ ਪ੍ਰਣਾਲੀ ਬਣਾਓ।',
    waterConservation: 'ਪਾਣੀ ਦੀ ਬਚਤ',
    waterDesc: 'ਛੋਟੇ ਖੇਤਾਂ ਲਈ ਸਧਾਰਨ ਸਿੰਚਾਈ ਅਤੇ ਬਰਸਾਤ ਦੇ ਪਾਣੀ ਦੀ ਵਾਢੀ ਤਕਨੀਕਾਂ। ਪਾਣੀ ਬਚਾਓ, ਖਰਚਾ ਬਚਾਓ।',
    pestManagement: 'ਕੀੜੇ ਪ੍ਰਬੰਧਨ',
    pestDesc: 'ਸਖ਼ਤ ਰਸਾਇਣਾਂ ਤੋਂ ਬਿਨਾਂ ਕੀੜਿਆਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰਨ ਅਤੇ ਫਸਲਾਂ ਦੀ ਰੱਖਿਆ ਕਰਨ ਲਈ ਘੱਟ ਲਾਗਤ ਵਾਲੇ ਕੁਦਰਤੀ ਤਰੀਕੇ।',
    agriculturePlans: 'ਖੇਤੀਬਾੜੀ ਯੋਜਨਾਵਾਂ',
    viewDetails: 'ਵੇਰਵੇ ਵੇਖੋ',
    selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
  },
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en')

  const t = (key) => {
    return translations[language][key] || translations.en[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translations }}>
      {children}
    </LanguageContext.Provider>
  )
}
